import PDFDocument from "pdfkit";
import { LessonSchema } from "@/lib/schema";
import type { LessonOptions } from "@/lib/schema";

export const runtime = "nodejs";

export async function POST(request: Request) {
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return new Response("Invalid JSON", { status: 400 });
  }

  const b = body as Record<string, unknown>;
  const parsed = LessonSchema.safeParse(b?.lesson);
  if (!parsed.success) {
    return new Response("Invalid lesson data", { status: 422 });
  }

  const lesson = parsed.data;
  const options: LessonOptions = {
    level: (b?.options as LessonOptions)?.level ?? "B1",
    style: (b?.options as LessonOptions)?.style ?? "teacher",
    showGapFillAnswers: (b?.options as LessonOptions)?.showGapFillAnswers ?? true,
  };

  let buffer: Buffer;
  try {
    buffer = await new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ size: "A4", margin: 56 });
      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const W = doc.page.width - 112;

      doc.fontSize(22).font("Helvetica-Bold").fillColor("#1a1a1a").text("ESL Lesson", { align: "left" });
      doc.fontSize(10).font("Helvetica").fillColor("#666666")
        .text(`Generated by YouTube to ESL Lesson Generator  -  Level: ${options.level}`, { align: "left" });
      doc.moveDown(1.5);
      doc.moveTo(56, doc.y).lineTo(56 + W, doc.y).strokeColor("#dddddd").stroke();
      doc.moveDown(1);

      function section(title: string) {
        doc.moveDown(0.8);
        doc.fontSize(13).font("Helvetica-Bold").fillColor("#111111").text(title.toUpperCase());
        doc.moveTo(56, doc.y + 3).lineTo(56 + W, doc.y + 3).strokeColor("#cccccc").stroke();
        doc.moveDown(0.6);
      }

      section("Summary");
      doc.fontSize(11).font("Helvetica").fillColor("#222222").text(lesson.summary, { lineGap: 4 });

      section("Vocabulary");
      lesson.vocabulary.forEach((item, i) => {
        doc.fontSize(11).font("Helvetica-Bold").fillColor("#222222")
          .text(`${i + 1}.  ${item.word}`, { continued: true })
          .font("Helvetica").fillColor("#444444").text(`  -  ${item.meaning}`);
        doc.fontSize(10).font("Helvetica-Oblique").fillColor("#666666")
          .text(`     ${item.example}`, { lineGap: 2 });
        doc.moveDown(0.3);
      });

      section("Comprehension Questions");
      lesson.questions.forEach((q, i) => {
        doc.fontSize(11).font("Helvetica").fillColor("#222222").text(`${i + 1}.  ${q}`, { lineGap: 4 });
        doc.moveDown(0.2);
      });

      section("Gap Fill Exercise");
      lesson.gapFill.forEach((item, i) => {
        doc.fontSize(11).font("Helvetica").fillColor("#222222")
          .text(`${i + 1}.  ${item.sentenceWithBlank}`, { lineGap: 2 });
        if (options.showGapFillAnswers) {
          doc.fontSize(10).font("Helvetica-Bold").fillColor("#4f46e5")
            .text(`     Answer: ${item.answer}`, { lineGap: 2 });
        }
        doc.moveDown(0.3);
      });

      doc.moveDown(2);
      doc.fontSize(9).font("Helvetica").fillColor("#aaaaaa")
        .text(`Level: ${options.level}  -  ${new Date().toLocaleDateString()}`, { align: "center" });

      doc.end();
    });
  } catch (err) {
    console.error("[/api/export] PDF generation failed:", err);
    return new Response("PDF generation failed", { status: 500 });
  }

  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": 'attachment; filename="esl-lesson.pdf"',
    },
  });
}
