import PDFDocument from "pdfkit";
import type { Lesson, LessonOptions } from "@/lib/schema";

const MARGIN = 56;
const COLOR_TITLE = "#1a1a1a";
const COLOR_SUBTITLE = "#666666";
const COLOR_DIVIDER = "#dddddd";
const COLOR_SECTION = "#111111";
const COLOR_SECTION_RULE = "#cccccc";
const COLOR_BODY = "#222222";
const COLOR_BODY_LIGHT = "#444444";
const COLOR_ITALIC = "#666666";
const COLOR_ACCENT = "#4f46e5";
const COLOR_FOOTER = "#aaaaaa";

export function buildPdf(lesson: Lesson, options: LessonOptions): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: MARGIN });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const W = doc.page.width - MARGIN * 2;

    doc.fontSize(22).font("Helvetica-Bold").fillColor(COLOR_TITLE).text("ESL Lesson", { align: "left" });
    doc.fontSize(10).font("Helvetica").fillColor(COLOR_SUBTITLE)
      .text(`Generated by YouTube to ESL Lesson Generator  -  Level: ${options.level}`, { align: "left" });
    doc.moveDown(1.5);
    doc.moveTo(MARGIN, doc.y).lineTo(MARGIN + W, doc.y).strokeColor(COLOR_DIVIDER).stroke();
    doc.moveDown(1);

    function section(title: string) {
      doc.moveDown(0.8);
      doc.fontSize(13).font("Helvetica-Bold").fillColor(COLOR_SECTION).text(title.toUpperCase());
      doc.moveTo(MARGIN, doc.y + 3).lineTo(MARGIN + W, doc.y + 3).strokeColor(COLOR_SECTION_RULE).stroke();
      doc.moveDown(0.6);
    }

    section("Summary");
    doc.fontSize(11).font("Helvetica").fillColor(COLOR_BODY).text(lesson.summary, { lineGap: 4 });

    section("Vocabulary");
    lesson.vocabulary.forEach((item, i) => {
      doc.fontSize(11).font("Helvetica-Bold").fillColor(COLOR_BODY)
        .text(`${i + 1}.  ${item.word}`, { continued: true })
        .font("Helvetica").fillColor(COLOR_BODY_LIGHT).text(`  -  ${item.meaning}`);
      doc.fontSize(10).font("Helvetica-Oblique").fillColor(COLOR_ITALIC)
        .text(`     ${item.example}`, { lineGap: 2 });
      doc.moveDown(0.3);
    });

    section("Comprehension Questions");
    lesson.questions.forEach((q, i) => {
      doc.fontSize(11).font("Helvetica").fillColor(COLOR_BODY).text(`${i + 1}.  ${q}`, { lineGap: 4 });
      doc.moveDown(0.2);
    });

    section("Gap Fill Exercise");
    lesson.gapFill.forEach((item, i) => {
      doc.fontSize(11).font("Helvetica").fillColor(COLOR_BODY)
        .text(`${i + 1}.  ${item.sentenceWithBlank}`, { lineGap: 2 });
      if (options.showGapFillAnswers) {
        doc.fontSize(10).font("Helvetica-Bold").fillColor(COLOR_ACCENT)
          .text(`     Answer: ${item.answer}`, { lineGap: 2 });
      }
      doc.moveDown(0.3);
    });

    doc.moveDown(2);
    doc.fontSize(9).font("Helvetica").fillColor(COLOR_FOOTER)
      .text(`Level: ${options.level}  -  ${new Date().toLocaleDateString()}`, { align: "center" });

    doc.end();
  });
}
